[31mCMake Error at /home/younlea/ros2_humble/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name message
  --arguments-file
  /home/younlea/source/ros_test/ros2_humble_test/TaskManager_topic_srv/message/build/message/rosidl_adapter__arguments__message.json
  --output-dir
  /home/younlea/source/ros_test/ros2_humble_test/TaskManager_topic_srv/message/build/message/rosidl_adapter/message
  --output-file
  /home/younlea/source/ros_test/ros2_humble_test/TaskManager_topic_srv/message/build/message/rosidl_adapter/message.idls)
  returned error code 1:

  Error processing 'int32 AB' of 'message/DataAB': ''AB' is an invalid field
  name.  It should have the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/younlea/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/younlea/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/younlea/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/home/younlea/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/home/younlea/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
      fields.append(Field(
    File "/home/younlea/ros2_humble/install/rosidl_adapter/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 354, in __init__
      raise NameError(

  NameError: 'AB' is an invalid field name.  It should have the pattern
  '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'

Call Stack (most recent call first):
  /home/younlea/ros2_humble/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:16 (rosidl_generate_interfaces)

[0m
